# Generated by Django 4.2.3 on 2023-08-05 20:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Dragonfly',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('specific_name', models.CharField(max_length=32)),
                ('common_name', models.CharField(max_length=32)),
                ('wikipedia_url', models.URLField(max_length=256)),
                ('photos_url', models.URLField(max_length=256)),
            ],
        ),
        migrations.CreateModel(
            name='Find',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('longitude', models.FloatField()),
                ('latitude', models.FloatField()),
                ('comment', models.CharField(max_length=256)),
                ('photo_url', models.URLField(max_length=256)),
                ('dragonfly', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='main.dragonfly')),
            ],
        ),
    ]
