# Generated by Django 4.2.3 on 2023-08-17 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finds', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='find',
            name='confirmed',
            field=models.BooleanField(default=False),
        ),
    ]
