# Generated by Django 4.2.3 on 2023-08-06 15:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finds', '0002_alter_find_dragonfly'),
    ]

    operations = [
        migrations.AddField(
            model_name='find',
            name='publication_date',
            field=models.DateTimeField(default=datetime.datetime.now, verbose_name='date published'),
        ),
    ]
