# Generated by Django 4.2.3 on 2023-08-17 15:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('finds', '0003_find_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='find',
            name='latitude',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='find',
            name='longitude',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
