# Generated by Django 4.2.3 on 2023-08-17 16:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('finds', '0005_alter_find_photo'),
    ]

    operations = [
        migrations.AlterField(
            model_name='find',
            name='dragonfly',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='finds.dragonfly'),
        ),
        migrations.AlterField(
            model_name='find',
            name='photo',
            field=models.ImageField(upload_to='photos/'),
        ),
    ]
